function build_results = build_windows
%BUILD_WINDOWS Build and package Black Hole Minesweeper for Windows.
% Requires MATLAB Compiler. Friends who install the result do not need
% MATLAB; the web installer downloads the matching free MATLAB Runtime.

project_dir = fileparts(mfilename('fullpath'));
original_dir = pwd;
restore_dir = onCleanup(@() cd(original_dir));
cd(project_dir);

release_dir = fullfile(project_dir,'release');
build_dir = fullfile(release_dir,'build');
installer_dir = fullfile(release_dir,'installer');

if isfolder(build_dir) || isfolder(installer_dir)
    error('BlackHoleMinesweeper:ReleaseExists', ...
        ['A previous release build exists. Rename or remove the release ' ...
         'folder before building again:\n%s'],release_dir);
end

if ~isfolder(release_dir)
    mkdir(release_dir);
end

fprintf('Building the standalone Windows application...\n');
build_results = compiler.build.standaloneWindowsApplication( ...
    fullfile(project_dir,'BlackHoleMinesweeper.m'), ...
    'AdditionalFiles',fullfile(project_dir,'assets'), ...
    'ExecutableName','BlackHoleMinesweeper', ...
    'ExecutableVersion','1.1.0.0', ...
    'OutputDir',build_dir);

fprintf('Creating the web installer...\n');
compiler.package.installer(build_results, ...
    'ApplicationName','Black Hole Minesweeper', ...
    'AuthorName','Dan Egert', ...
    'InstallerName','BlackHoleMinesweeperInstaller', ...
    'RuntimeDelivery','web', ...
    'Summary','Play Minesweeper against a Monte Carlo alien agent.', ...
    'Version','1.1.0', ...
    'OutputDir',installer_dir);

fprintf('\nPackaging complete. Share the installer found here:\n%s\n', ...
    installer_dir);

end
